spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:mysql://localhost:3306/patient_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 8082

grpc:
  server:
    port: 9090

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
